---
title: "JH-1"
output: html_document
---
# Instalación de librerias
install.packages("httr")
install.packages("XML")

# Validación de librerías
library(httr)
library(XML)
library(ggplot2)




#Pregunta 1
Queremos programar un programa de tipo web scrapping con el que podamos obtener 
una página web, mediante su URL, y poder analizar su contenido HTML con tal de extraer 
datos e información específica. 
Nuestro programa ha de ser capaz de cumplir con los siguientes pasos:

1. Descargar la página web de la URL indicada, y almacenarlo en un formato de R apto para ser tratado. 
El primer paso para realizar tareas de crawling y scraping es poder descargar los datos de la web. Para esto usaremos la capacidad de R y de sus librerías (httr y XML) para descargar webs y almacenarlas en variables que podamos convertir en un formato fácil de analizar (p.e. de HTML a XML). 

# URL objetivo
url <- "https://www.mediawiki.org/wiki/MediaWiki"

# Descargar HTML
response <- GET(url)

#Validar descarga de la web
substr(html_content, 1, 500)

#Convertir a texto
html_content <- content(response, as ="text", encoding = "UTF-8")

# Parsear a XML
library(XML)

doc <- htmlParse(html_content, asText = TRUE, encoding = "UTF-8")

#####
Pregunta 2
# Analizar el contenido de la web, buscando el título de la página (que en HTML se etiqueta como “title”). 
En las cabeceras web encontramos información como el título, los ficheros de estilo visual, y meta-información como el nombre del autor de la página, una descripción de esta, el tipo de codificación de esta, o palabras clave que indican qué tipo de información contiene la página. Una vez descargada la página, y convertida a un formato analizable (como XML), buscaremos los elementos de tipo “title”. P.e. “<title>Titulo de Página</title>”. 


# 2. Extraer el titulo de la página
# Extraer el titulo
title <- xpathSApply(doc, "//title",xmlValue)
title

#######
3. Analizar el contenido de la web, buscando todos los enlaces (que en HTML se etiquetan como “a”), buscando el texto del enlace, así como la URL. Vamos a extraer, usando las funciones de búsqueda XML, todos los enlaces que salen de esta página con tal de listarlos y poder descargarlas más tarde. Sabemos que estos son elementos de tipo “<a>”, que tienen el atributo “href” para indicar la URL del enlace. P.e. “<a href = ‘enlace’>Texto del Enlace</a>”. Del enlace nos quedaremos con la URL de destino y con el valor del enlace (texto del enlace). 

# 3. Extracción de enlaces
# Nodos
links_nodes <- xpathSApply(doc, "//a")

#Extraer URLS
urls <- sapply(links_nodes, xmlGetAttr, "href")

#Extraer texto de la URL
texts <- sapply(links_nodes,xmlValue)

#Null a NA
urls[sapply(urls, is.null)] <- NA
texts[sapply(texts, is.null)] <- NA

# Convertir el vector
urls <- unlist(urls)
texts <- unlist(texts)


#
4. Generar una tabla con cada enlace encontrado, indicando el texto que acompaña el enlace, nùmero de veces que aparece un enlace con ese mismo objetiv
#
#Limpiar
texts <- gsub("[\r\n\t]+", " ", texts)
texts <- gsub("\\s+", " ", texts)
texts <- trimws(texts)
texts[texts == ""] <- NA

# Crear data frame base
df_links <- data.frame (
url = urls,
texto = texts,
stringsAsFactors = FALSE
)

# Eliminar URLS vacias
df_links <- df_links[!is.na(df_links$url) & df_links$url !="", ]

#Filtro de datos sucios

df_links <- df_links[
!is.na(df_links$url) &
df_links$url != "" &
df_links$url != "#" &
!is.na(df_links$texto),
]

#Filtro de textos pequeños
df_links <- df_links[nchar(df_links$texto) > 2, ]


# 4. Veces que aparece un enlace
# Conteo de URLs
url_counts <- table(df_links$url)

#Convertir a data frame
url_counts_df <- data.frame(
url = names(url_counts),
veces = as.numeric(url_counts),
stringsAsFactors = FALSE
)

# Unir el conteo 
df_final <- merge(df_links, url_counts_df, by ="url")



#Ver algunas filas
df_final <- df_final[order(-df_final$veces), ]
head(df_final, 10)
head (url_counts)


# 5 Para cada enlace, seguirlo e indicar si está activo (podemos usar el código de  status HTTP al hacer una petición a esa URL). 
En este paso podemos usar la función HEAD de la librería “httr”, que en vez de 
descargarse la página como haría GET, solo consultamos los atributos de la 
página o fichero destino. 
HEAD nos retorna una lista de atributos, y de entre estos hay uno llamado 
“header” que contiene más atributos sobre la página buscada. Si seguimos 
podemos encontrar el “status_code” en “resultado$status_code”. El 
“status_code” nos indica el resultado de la petición de página o fichero. Este 
código puede indicar que la petición ha sido correcta (200), que no se ha 
encontrado (404), que el acceso está restringido (403), etc. 
Actividad Evaluable 2 
3 
Seminario Internacional en Herramientas y Técnicas de Detección de Ciberamenazas - 2026 
• Tened en cuenta que hay enlaces con la URL relativa, con forma 
“/xxxxxx/xxxxx/a.html”. En este caso, podemos indicarle como “handle” el 
dominio de la página que estamos tratando, o añadirle el dominio a la URL 
con la función “paste”.  
• Tened en cuenta que puede haber enlaces externos con la URL absoluta, con 
forma “http://xxxxxx/xxxx/a.html” (o https), que los trataremos 
directamente. 
• Tened en cuenta que puede haber enlaces que apunten a subdominios 
distintos, con forma “//subdominio/xxxx/xxxx/a.html”. En este caso 
podemos adjuntarle el prefijo “https:” delante, convirtiendo la URL en 
absoluta. 
• Tened en cuenta URLS internas con tags, como por ejemplo “#search-p”. 
Estos apuntan a la misma página en la que estamos, pero diferente altura de 
página. Equivale a acceder a la URL relativa de la misma página en la que 
estamos. 
Es recomendado poner un tiempo de espera entre petición y petición de pocos 
segundos (comando “Sys.sleep”), para evitar ser “baneados” por el servidor. Para 
poder examinar las URLs podemos usar expresiones regulares, funciones como 
“grep”, o mirar si en los primeros caracteres de la URL encontramos “//” o “http”. 
Para tratar las URLs podemos usar la ayuda de la función “paste”, para manipular 
cadenas de caracteres y poder añadir prefijos a las URLs si fuera necesario.


#Funcion para normalizar la URL
normalize_url <- function(links, base_url){
if (is.na(links)) return(NA)

if(grepl("^http, link)){
return(link)
} else if (grepl("^//", link)) {
return(paste0("https:" link))
} else if (grepl("^#", links)){
return(base_url)
} else{
return(paste0(base_url, link))
}
}

base <- "https://www.mediawiki.org"

#Aplicar normalizacion
df_final$url_full <- sapply(df_final$url, normalize_url, base_url=base)

#obtener status HTTP
df_final$status <- sapply(df_final$url_full, function(link){
tryCatch({
if (is.na(link)) return(NA)
res <- HEAD(link)
Sys.sleep(1) 
status_code(res)
}, error = function(e) )
}







